check cd/19

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,34 +36,34 @@ jobs:
           set -e  # Stop execution on error
           docker-compose -f docker-compose.yml up --build --abort-on-container-exit
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build  # Wait for the build job to complete successfully
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Set up SSH
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-
-
-      - name: Print Server Info
-        env:
-          SERVER_IP: ${{ secrets.SERVER_IP }}
-          USERNAME: ${{ secrets.USERNAME }}
-        run: |
-          echo "SERVER_IP: $SERVER_IP"
-          echo "USERNAME: $USERNAME"
-
-      - name: Deploy to Server
-        env:
-          SERVER_IP: ${{ secrets.SERVER_IP }}
-          USERNAME: ${{ secrets.USERNAME }}
-        run: |
-          set -e  # Stop execution on error
-          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
-          ssh -vvv -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "echo 'SSH Connection Successful'"
+#  deploy:
+#    runs-on: ubuntu-latest
+#    needs: build  # Wait for the build job to complete successfully
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Set up SSH
+#        run: |
+#          mkdir -p ~/.ssh
+#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+#          chmod 600 ~/.ssh/id_rsa
+#
+#
+#      - name: Print Server Info
+#        env:
+#          SERVER_IP: ${{ secrets.SERVER_IP }}
+#          USERNAME: ${{ secrets.USERNAME }}
+#        run: |
+#          echo "SERVER_IP: $SERVER_IP"
+#          echo "USERNAME: $USERNAME"
+#
+#      - name: Deploy to Server
+#        env:
+#          SERVER_IP: ${{ secrets.SERVER_IP }}
+#          USERNAME: ${{ secrets.USERNAME }}
+#        run: |
+#          set -e  # Stop execution on error
+#          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
+#          ssh -vvv -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP "echo 'SSH Connection Successful'"
